/**
 * HiringAI — Recruiting OS template for fast-moving startups.
 *
 * Audience: founders and early hiring leads at seed–Series B startups who
 * need to ship hires quickly, often without a dedicated recruiter, and want
 * AI to do the heavy lifting end-to-end.
 *
 * Apply this branding by importing it into your app's runtime config and
 * spreading it over the default theme/copy.
 */

export const branding = {
  // ── Identity ───────────────────────────────────────────────────────────────
  productName: "HiringAI",
  productTagline: "Your AI hiring co-founder. Source, screen, decide — fast.",
  productDescription:
    "HiringAI is the all-in-one hiring tool for startups. Describe the role in one paragraph and HiringAI sources, screens, scores, and shortlists candidates so founders can spend their time on the final interview, not the funnel.",
  domain: "hiringai.dev",
  supportEmail: "founders@hiringai.dev",

  // ── Audience ───────────────────────────────────────────────────────────────
  primaryUser: "founder",
  primaryUserPlural: "founders & hiring leads",
  reportAudience: "founder",

  // ── Terminology overrides ──────────────────────────────────────────────────
  // Startup-native, low-jargon vocabulary. "Hire", not "requisition".
  terms: {
    candidate: "person",
    candidates: "people",
    job: "hire",
    jobs: "hires",
    hiringManager: "founder",
    report: "shortlist",
    pipeline: "funnel",
    application: "intro",
    workflow: "auto-pilot",
  },

  // ── Visual identity ────────────────────────────────────────────────────────
  // Bold, modern, AI-native. High-contrast dark surface with electric accent.
  colors: {
    primary: "#0B0B12",        // near-black surface, modern AI product feel
    primaryFg: "#F5F7FA",
    accent: "#7C5CFF",         // electric violet — AI signal color
    accentFg: "#0B0B12",
    success: "#22D3A4",        // mint, energetic
    warning: "#FBBF24",
    danger: "#FB7185",
    surface: "#0F0F18",
    surfaceMuted: "#1A1B26",
    border: "#262838",
    text: "#F5F7FA",
    textMuted: "#9CA3B5",
  },

  // ── Typography ─────────────────────────────────────────────────────────────
  // Geometric sans for product, mono accents for that "AI tool" feel.
  fonts: {
    sans: '"Geist", "Inter", system-ui, sans-serif',
    serif: '"Source Serif 4", Georgia, serif',
    mono: '"Geist Mono", "JetBrains Mono", ui-monospace, monospace',
  },

  // ── Default report framing ─────────────────────────────────────────────────
  reportDefaults: {
    coverTitle: "Your Shortlist",
    coverSubtitle: "Generated by HiringAI",
    decisionSummaryTitle: "Shortlist",
    nextActionsTitle: "Do These Things Today",
    footerNote:
      "Built by HiringAI — your AI hiring co-founder. Reply to this report to chat with the agent.",
  },

  // ── Pipeline stage labels ──────────────────────────────────────────────────
  // Compressed, founder-friendly funnel.
  stageLabels: {
    Sourced: "Found",
    Contacted: "Reached out",
    Screened: "Talked",
    Interview: "Founder chat",
    Offer: "Offer out",
    Hired: "Signed",
    Rejected: "Pass",
  },

  // ── Feature emphasis ───────────────────────────────────────────────────────
  // Founders want speed, autonomy, and one-button workflows.
  featureFlags: {
    autoSource: true,                // agent runs sourcing without prompting
    autoOutreach: true,              // agent drafts + sends first messages
    chatWithShortlist: true,         // "ask the AI" sidebar over the report
    slackInbox: true,                // candidate replies land in Slack
    oneClickHireDecision: true,      // green "Make Offer" button on the report
    skipApprovalFlow: true,          // no approvals, no req intake forms
    bringYourOwnLLM: true,           // founders bring OpenAI/Anthropic keys
    weeklyDigestEmail: true,         // "your funnel this week" auto-email
  },
} as const;

export type Branding = typeof branding;
export default branding;
