/**
 * HireFlow — Recruiting OS template for HR SaaS at mid-market & enterprise.
 *
 * Audience: in-house Talent Acquisition teams at 200–10,000 person companies
 * who run structured, compliance-aware hiring across many open roles.
 *
 * Apply this branding by importing it into your app's runtime config and
 * spreading it over the default theme/copy.
 */

export const branding = {
  // ── Identity ───────────────────────────────────────────────────────────────
  productName: "HireFlow",
  productTagline: "Structured hiring that scales with your TA team.",
  productDescription:
    "HireFlow is a hiring platform for in-house Talent Acquisition teams. Standardize evaluation rubrics, automate candidate screening with explainable AI, and give every hiring manager a defensible report — without leaving your ATS workflow.",
  domain: "hireflow.io",
  supportEmail: "support@hireflow.io",

  // ── Audience ───────────────────────────────────────────────────────────────
  primaryUser: "talent acquisition partner",
  primaryUserPlural: "TA team",
  reportAudience: "hiring manager",

  // ── Terminology overrides ──────────────────────────────────────────────────
  // Mid-market HR teams use formal, ATS-aligned vocabulary.
  terms: {
    candidate: "candidate",
    candidates: "candidates",
    job: "requisition",
    jobs: "requisitions",
    hiringManager: "hiring manager",
    report: "evaluation report",
    pipeline: "pipeline",
    application: "application",
    workflow: "screening workflow",
  },

  // ── Visual identity ────────────────────────────────────────────────────────
  // Calm, trustworthy, enterprise-friendly. Teal-blue + soft slate.
  colors: {
    primary: "#1F6FA8",        // workday-adjacent blue, neutral and trusted
    primaryFg: "#FFFFFF",
    accent: "#14B8A6",         // teal — highlights for "AI assisted" elements
    accentFg: "#022C2A",
    success: "#16A34A",
    warning: "#D97706",
    danger: "#DC2626",
    surface: "#F8FAFC",
    surfaceMuted: "#EEF2F6",
    border: "#D8DEE7",
    text: "#0F172A",
    textMuted: "#64748B",
  },

  // ── Typography ─────────────────────────────────────────────────────────────
  fonts: {
    sans: '"Inter", "Segoe UI", system-ui, sans-serif',
    serif: '"Source Serif 4", Georgia, serif',
    mono: '"JetBrains Mono", ui-monospace, monospace',
  },

  // ── Default report framing ─────────────────────────────────────────────────
  reportDefaults: {
    coverTitle: "Candidate Evaluation Report",
    coverSubtitle: "Prepared by Talent Acquisition",
    decisionSummaryTitle: "Hiring Recommendation Summary",
    nextActionsTitle: "Next Steps in the Hiring Process",
    footerNote:
      "Internal use only. Generated by HireFlow — evaluation reasoning is auditable and stored for compliance review.",
  },

  // ── Pipeline stage labels ──────────────────────────────────────────────────
  // Mirror the standard ATS funnel that hiring managers already know.
  stageLabels: {
    Sourced: "New",
    Contacted: "Recruiter Screen",
    Screened: "Phone Screen",
    Interview: "Onsite / Panel",
    Offer: "Offer",
    Hired: "Hired",
    Rejected: "Rejected",
  },

  // ── Feature emphasis ───────────────────────────────────────────────────────
  // Enterprise TA cares about governance, integration, and reporting.
  featureFlags: {
    ssoRequired: true,                  // SAML/OIDC at the front door
    auditLogExport: true,               // every AI decision logged & exportable
    biasReviewBanner: true,             // surface fairness disclosures inline
    atsIntegration: true,               // Greenhouse / Lever / Workday hooks
    requisitionApprovalWorkflow: true,  // intake → approval → publish
    structuredScorecards: true,         // panelist scorecards required pre-offer
    eeocReporting: true,                // demographic reporting dashboards
  },
} as const;

export type Branding = typeof branding;
export default branding;
