import { Router, type IRouter } from "express";
import applicationsRouter from "./applications";
import brandingRouter from "./branding";
import candidateNotesRouter from "./candidate-notes";
import candidatesRouter from "./candidates";
import deliberationsRouter from "./deliberations";
import emailStatusChangesRouter from "./email-status-changes";
import healthRouter from "./health";
import importRouter from "./import";
import integrationsScoutRouter from "./integrations-scout";
import jobsRouter from "./jobs";
import providersRouter from "./providers";
import reportsRouter from "./reports";
import savedRunComparisonsRouter from "./saved-run-comparisons";
import settingsRouter from "./settings";
import storageRouter from "./storage";
import telemetryRouter from "./telemetry";
import workflowsRouter from "./workflows";

const router: IRouter = Router();

router.use(applicationsRouter);
router.use(brandingRouter);
router.use(candidateNotesRouter);
router.use(candidatesRouter);
router.use(deliberationsRouter);
router.use(emailStatusChangesRouter);
router.use(healthRouter);
router.use(importRouter);
router.use(integrationsScoutRouter);
router.use(jobsRouter);
router.use(providersRouter);
router.use(reportsRouter);
router.use(savedRunComparisonsRouter);
router.use(settingsRouter);
router.use(storageRouter);
router.use(telemetryRouter);
router.use(workflowsRouter);

export default router;
