import {
  db,
  agentRunsTable,
  agentLogsTable,
  aiEvaluationsTable,
  jobInsightsTable,
  shortlistsTable,
  jobsTable,
  candidatesTable,
  applicationsTable,
} from "@workspace/db";
import type { VariantCriteria, DataMode } from "@workspace/db";
import { eq, ne, and, inArray } from "drizzle-orm";
import { logger } from "../../lib/logger";
import { resolveProvider, resolveSourcingProvider, resolveEnrichmentProvider } from "./providers";
import type { JobInsightResult, CandidateMatchResult, ShortlistResult } from "./engine-types";
import type { SourcingCandidate, EnrichmentResult } from "./providers";

export type { JobInsightResult, CandidateMatchResult, ShortlistResult };

// ── Source tag constants ──────────────────────────────────────────────────────

/** Candidates generated by the AI mock sourcing provider */
const SOURCE_MOCK = "Mock";
/** Candidates sourced via a Twin webhook provider */
const SOURCE_TWIN = "Twin";
/** Legacy mock source tag (from before strict data mode was introduced) */
const SOURCE_LEGACY_MOCK = "AI Generated / Mock Sourcing";

function isMockSource(source: string | null): boolean {
  return source === SOURCE_MOCK || source === SOURCE_LEGACY_MOCK;
}

// ── helpers ──────────────────────────────────────────────────────────────────

async function logStep(
  runId: number,
  step: string,
  status: "pending" | "running" | "completed" | "failed",
  input?: unknown,
  output?: unknown,
) {
  await db
    .insert(agentLogsTable)
    .values({ runId, step, status, input: input ?? null, output: output ?? null });
}

async function setRunStatus(runId: number, status: "running" | "completed" | "failed") {
  await db
    .update(agentRunsTable)
    .set({ status, updatedAt: new Date() })
    .where(eq(agentRunsTable.id, runId));
}

async function setRunDataMode(runId: number, dataMode: DataMode) {
  await db
    .update(agentRunsTable)
    .set({ dataMode, updatedAt: new Date() })
    .where(eq(agentRunsTable.id, runId));
}

// ── STEP 0: Sourcing (optional) ───────────────────────────────────────────────

async function runSourcing(
  runId: number,
  jobId: number,
  job: { title: string; description: string; location: string; seniority: string; mustHaveSkills: string[] },
  insight: JobInsightResult,
  sourceTag: string,
  forceProvider?: import("./providers").AgentProvider,
): Promise<number[]> {
  await logStep(runId, "sourcing", "running", { jobTitle: job.title, sourceTag });

  const provider = forceProvider ?? (await resolveSourcingProvider()).provider;
  logger.info({ runId, step: "sourcing", provider: provider.name, sourceTag }, "Sourcing step dispatched");

  try {
    const candidates = (await provider.run({
      step: "sourcing",
      runId,
      jobId,
      payload: { job, insight },
    })) as SourcingCandidate[];

    // Deduplicate by email against existing candidates
    const existing = await db.select({ email: candidatesTable.email }).from(candidatesTable);
    const existingEmails = new Set(existing.map((c) => c.email.toLowerCase()));

    const newCandidateIds: number[] = [];
    for (const c of candidates) {
      const emailKey = c.email.toLowerCase();
      if (existingEmails.has(emailKey)) {
        logger.warn({ email: c.email }, "Sourcing skipped duplicate email");
        continue;
      }
      existingEmails.add(emailKey);

      const [inserted] = await db
        .insert(candidatesTable)
        .values({
          name: c.name,
          email: c.email,
          linkedIn: c.linkedinUrl || null,
          summary: c.summary || null,
          skills: c.skills,
          headline: c.headline || null,
          location: c.location || null,
          currentCompany: c.currentCompany || null,
          githubUrl: c.githubUrl || null,
          source: sourceTag,
        })
        .returning({ id: candidatesTable.id });

      newCandidateIds.push(inserted.id);

      // Create application at "Sourced" stage
      await db.insert(applicationsTable).values({
        jobId,
        candidateId: inserted.id,
        stage: "Sourced",
        notes: `AI Generated — ${c.evidence}\nPotential risks: ${c.potentialRisks}`,
      });
    }

    await logStep(runId, "sourcing", "completed", { jobTitle: job.title, provider: provider.name, sourceTag }, {
      generated: candidates.length,
      saved: newCandidateIds.length,
    });
    return newCandidateIds;
  } catch (err) {
    await logStep(runId, "sourcing", "failed", { jobTitle: job.title, provider: provider.name }, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 0b: Enrichment (optional) ───────────────────────────────────────────

/**
 * Returns true if a candidate needs enrichment — i.e. has sparse or placeholder data.
 * We only enrich candidates that are likely incomplete to avoid overwriting good data.
 */
function needsEnrichment(c: {
  source: string | null;
  summary: string | null;
  skills: string[];
  headline: string | null;
}): boolean {
  if (c.source === "LinkedIn Paste") return true;
  if (!c.summary || c.summary.startsWith("Imported from LinkedIn")) return true;
  if (c.skills.length === 0) return true;
  if (!c.headline) return true;
  return false;
}

async function runEnrichment(
  runId: number,
  jobId: number,
  job: { title: string; seniority: string; mustHaveSkills: string[] },
): Promise<void> {
  // Resolve provider — null means no provider is configured; enrichment is skipped
  const provider = await resolveEnrichmentProvider();
  if (!provider) {
    await logStep(runId, "enrichment", "failed", null, {
      note: "No enrichment provider is assigned. Configure one in Settings → Agent Providers → Workflow Step Assignments to enable enrichment.",
    });
    logger.info({ runId }, "Enrichment skipped: no provider configured");
    return;
  }

  // Only enrich candidates in this job's pipeline
  const jobApplications = await db
    .select({ candidateId: applicationsTable.candidateId })
    .from(applicationsTable)
    .where(eq(applicationsTable.jobId, jobId));

  if (jobApplications.length === 0) {
    logger.info({ runId }, "No candidates in pipeline — skipping enrichment");
    return;
  }

  const candidateIds = jobApplications.map((a) => a.candidateId);
  const allCandidates = await db
    .select()
    .from(candidatesTable)
    .where(inArray(candidatesTable.id, candidateIds));

  // Filter to only candidates with sparse / placeholder profiles
  const candidates = allCandidates.filter(needsEnrichment);

  if (candidates.length === 0) {
    logger.info({ runId }, "No candidates need enrichment — all profiles are already complete");
    await logStep(runId, "enrichment", "completed", { note: "All candidates already have complete profiles" }, {
      enriched: 0,
    });
    return;
  }

  await logStep(runId, "enrichment", "running", { candidateCount: candidates.length, provider: provider.name });
  logger.info({ runId, step: "enrichment", provider: provider.name, count: candidates.length }, "Enrichment step dispatched");

  const rawResponse = await provider.run({
    step: "enrichment",
    runId,
    jobId,
    payload: {
      candidates,
      jobContext: { title: job.title, seniority: job.seniority, mustHaveSkills: job.mustHaveSkills },
    },
  });

  logger.info(
    { runId, step: "enrichment", provider: provider.name, raw: JSON.stringify(rawResponse).slice(0, 500) },
    "Enrichment raw response",
  );

  const results = rawResponse as EnrichmentResult[];

  const now = new Date();
  let enrichedCount = 0;
  let partialCount = 0;
  let failedCount = 0;

  for (const r of results) {
    const confidence = typeof r.confidence === "number" ? Math.min(1, Math.max(0, r.confidence)) : 0;
    const missingSet = new Set<string>(Array.isArray(r.missingFields) ? r.missingFields : []);

    // Determine enrichment outcome based on confidence and missing fields
    const status: string =
      confidence >= 0.7 && missingSet.size === 0
        ? "enriched"
        : confidence >= 0.4
        ? "partial"
        : "failed";

    if (status === "enriched") enrichedCount++;
    else if (status === "partial") partialCount++;
    else failedCount++;

    // Only write fields that are actually present in the result and not listed as missing
    await db
      .update(candidatesTable)
      .set({
        ...(r.experienceSummary && !missingSet.has("summary") ? { summary: r.experienceSummary } : {}),
        ...(Array.isArray(r.skills) && r.skills.length > 0 && !missingSet.has("skills") ? { skills: r.skills } : {}),
        ...(r.enrichedHeadline && !missingSet.has("headline") ? { headline: r.enrichedHeadline } : {}),
        ...(r.currentCompany && !missingSet.has("currentCompany") ? { currentCompany: r.currentCompany } : {}),
        ...(r.location && !missingSet.has("location") ? { location: r.location } : {}),
        enrichedAt: now,
        enrichmentSource: provider.name,
        enrichmentConfidence: confidence,
        enrichmentStatus: status,
        updatedAt: now,
      })
      .where(eq(candidatesTable.id, r.candidateId));
  }

  logger.info(
    { runId, step: "enrichment", enrichedCount, partialCount, failedCount },
    "Enrichment normalized output",
  );

  await logStep(runId, "enrichment", "completed", { candidateCount: candidates.length, provider: provider.name }, {
    enriched: enrichedCount,
    partial: partialCount,
    failed: failedCount,
    avgConfidence: results.length > 0
      ? (results.reduce((s, r) => s + (typeof r.confidence === "number" ? r.confidence : 0), 0) / results.length).toFixed(2)
      : null,
  });
}

// ── STEP 1: Job Understanding ─────────────────────────────────────────────────

async function runJobUnderstanding(
  runId: number,
  jobId: number,
  job: { title: string; description: string; location: string; seniority: string; mustHaveSkills: string[] },
): Promise<JobInsightResult> {
  await logStep(runId, "job_understanding", "running", { jobTitle: job.title });

  const provider = await resolveProvider("job_understanding");
  logger.info({ runId, step: "job_understanding", provider: provider.name }, "Step dispatched");

  try {
    const result = (await provider.run({
      step: "job_understanding",
      runId,
      jobId,
      payload: { job },
    })) as JobInsightResult;

    await logStep(runId, "job_understanding", "completed", { jobTitle: job.title, provider: provider.name }, result);
    return result;
  } catch (err) {
    await logStep(runId, "job_understanding", "failed", { jobTitle: job.title, provider: provider.name }, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 2: Candidate Matching ────────────────────────────────────────────────

async function runCandidateMatching(
  runId: number,
  jobId: number,
  job: { title: string; description: string; mustHaveSkills: string[]; seniority: string },
  insight: JobInsightResult,
  candidates: Array<{ id: number; name: string; email: string; skills: string[]; summary: string | null }>,
): Promise<void> {
  await logStep(runId, "candidate_matching", "running", { candidateCount: candidates.length });

  const provider = await resolveProvider("candidate_matching");
  logger.info({ runId, step: "candidate_matching", provider: provider.name }, "Step dispatched");

  try {
    const results = (await provider.run({
      step: "candidate_matching",
      runId,
      jobId,
      payload: { job, insight, candidates },
    })) as CandidateMatchResult[];

    await Promise.all(
      results.map((r) =>
        db.insert(aiEvaluationsTable).values({
          runId,
          jobId,
          candidateId: r.candidateId,
          score: r.score,
          strengths: r.strengths,
          gaps: r.gaps,
          risks: r.risks,
          recommendation: r.recommendation,
          scoreBreakdown: r.scoreBreakdown ?? null,
        }),
      ),
    );

    await logStep(runId, "candidate_matching", "completed", { candidateCount: candidates.length, provider: provider.name }, {
      scores: results.map((r) => ({ name: r.candidateName, score: r.score, rec: r.recommendation })),
    });
  } catch (err) {
    await logStep(runId, "candidate_matching", "failed", { candidateCount: candidates.length, provider: provider.name }, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 3: Shortlist ─────────────────────────────────────────────────────────

async function runShortlist(
  runId: number,
  jobId: number,
  job: { title: string; description: string },
  insight: JobInsightResult,
  evaluations: Array<{
    candidateId: number;
    candidateName: string;
    score: number;
    recommendation: string;
    strengths: string[];
    gaps: string[];
  }>,
): Promise<void> {
  await logStep(runId, "shortlist", "running", { totalEvaluated: evaluations.length });

  const provider = await resolveProvider("shortlist_generation");
  logger.info({ runId, step: "shortlist_generation", provider: provider.name }, "Step dispatched");

  try {
    const top5 = [...evaluations].sort((a, b) => b.score - a.score).slice(0, 5);
    const summaries = (await provider.run({
      step: "shortlist_generation",
      runId,
      jobId,
      payload: { job, insight, evaluations: top5 },
    })) as ShortlistResult[];

    await db.insert(shortlistsTable).values({
      runId,
      jobId,
      rankedCandidateIds: top5.map((c) => c.candidateId),
      summaries,
    });

    await logStep(runId, "shortlist", "completed", { top5Count: top5.length, provider: provider.name }, { summaries });
  } catch (err) {
    await logStep(runId, "shortlist", "failed", {}, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── MAIN RUNNER ───────────────────────────────────────────────────────────────

export async function runWorkflowEngine(
  runId: number,
  jobId: number,
  options: {
    dataMode?: DataMode;
    runSourcing?: boolean;
    runEnrichment?: boolean;
    variantCriteria?: VariantCriteria;
  } = {},
) {
  const dataMode: DataMode = options.dataMode ?? "mock";

  try {
    await setRunStatus(runId, "running");
    logger.info(
      { runId, jobId, dataMode, runSourcing: options.runSourcing, runEnrichment: options.runEnrichment, isVariant: !!options.variantCriteria },
      "Workflow started",
    );

    const [job] = await db.select().from(jobsTable).where(eq(jobsTable.id, jobId));
    if (!job) throw new Error(`Job ${jobId} not found`);

    // Apply variant criteria overrides if this is a variant run
    const vc = options.variantCriteria;
    const effectiveJob = vc
      ? {
          ...job,
          seniority: vc.seniority ?? job.seniority,
          mustHaveSkills: vc.mustHaveSkills ?? job.mustHaveSkills,
          description: vc.focusNote
            ? `${job.description}\n\n[Variant focus]: ${vc.focusNote}`
            : job.description,
        }
      : job;

    // Step 1: Job Understanding (always runs first)
    const insight = await runJobUnderstanding(runId, jobId, effectiveJob);
    await db.insert(jobInsightsTable).values({
      runId,
      jobId,
      mustHaveSkills: insight.mustHaveSkills,
      seniority: insight.seniority,
      evaluationCriteria: insight.evaluationCriteria,
      idealCandidateProfile: insight.idealCandidateProfile,
    });

    // Step 0: Sourcing (optional, runs after job understanding, before matching)
    if (options.runSourcing) {
      const { provider: sourcingProvider, isTwin } = await resolveSourcingProvider();

      if (dataMode === "real") {
        // Real mode: only Twin providers are allowed for sourcing
        if (!isTwin) {
          logger.warn({ runId }, "Real mode: no Twin provider assigned to sourcing — skipping sourcing step");
          await logStep(runId, "sourcing", "failed", null, {
            note: "Skipped: real data mode requires a Twin webhook provider for sourcing. Assign one in Settings → Providers.",
          });
        } else {
          // Real mode with Twin provider → source and tag as "Twin"
          try {
            await runSourcing(runId, jobId, effectiveJob, insight, SOURCE_TWIN, sourcingProvider);
          } catch (err) {
            // Twin sourcing failed in real mode → demote to fallback
            logger.error({ runId, err }, "Real mode: Twin sourcing failed — demoting run to fallback mode");
            await setRunDataMode(runId, "fallback");
            await logStep(runId, "sourcing", "failed", null, {
              error: err instanceof Error ? err.message : String(err),
              note: "Run demoted to fallback: Twin provider failed. Continuing with existing imported candidates.",
            });
          }
        }
      } else {
        // Mock mode: only use native mock sourcing (never Twin in mock mode)
        if (isTwin) {
          logger.warn({ runId }, "Mock mode: Twin provider is assigned to sourcing but data mode is mock — using native mock sourcing instead");
        }
        const { NativeOpenAISourcingProvider } = await import("./providers/native-openai-sourcing");
        const mockProvider = new NativeOpenAISourcingProvider(-1, "Native OpenAI Sourcing (mock)");
        try {
          await runSourcing(runId, jobId, effectiveJob, insight, SOURCE_MOCK, mockProvider);
        } catch (err) {
          logger.error({ runId, jobId, err }, "Mock sourcing failed — continuing with existing candidates");
          await logStep(runId, "sourcing", "failed", null, {
            error: err instanceof Error ? err.message : String(err),
            note: "Continuing workflow with existing candidates",
          });
        }
      }
    }

    // Step 0b: Enrichment (optional, runs after sourcing, before matching)
    if (options.runEnrichment) {
      try {
        await runEnrichment(runId, jobId, effectiveJob);
      } catch (err) {
        // Enrichment failures are non-fatal — log and continue with existing candidate data.
        // There is NO silent fallback to a native provider here (see registry.ts).
        logger.error({ runId, jobId, err }, "Enrichment step failed — continuing without enrichment");
        await logStep(runId, "enrichment", "failed", null, {
          error: err instanceof Error ? err.message : String(err),
          note: "Continuing workflow without enrichment. No fallback provider is used.",
        });
      }
    }

    // Re-read current data mode (may have been updated to "fallback" during sourcing)
    const [currentRun] = await db.select({ dataMode: agentRunsTable.dataMode }).from(agentRunsTable).where(eq(agentRunsTable.id, runId));
    const effectiveDataMode: DataMode = currentRun?.dataMode ?? dataMode;

    // Step 2: Candidate Matching — enforce data mode separation
    const allCandidates = await db.select().from(candidatesTable);

    let matchingCandidates: typeof allCandidates;
    if (effectiveDataMode === "real") {
      // Real mode: only non-mock candidates (imported + Twin)
      matchingCandidates = allCandidates.filter((c) => !isMockSource(c.source));
      if (matchingCandidates.length === 0) {
        logger.warn({ runId }, "Real mode: no imported or Twin-sourced candidates found — skipping matching");
      } else {
        logger.info({ runId, dataMode: effectiveDataMode, count: matchingCandidates.length }, "Real mode: matching non-mock candidates only");
      }
    } else if (effectiveDataMode === "fallback") {
      // Fallback mode: use all non-mock candidates (Twin failed, use whatever is imported)
      matchingCandidates = allCandidates.filter((c) => !isMockSource(c.source));
      if (matchingCandidates.length === 0) {
        logger.warn({ runId }, "Fallback mode: no imported candidates found — skipping matching");
      } else {
        logger.info({ runId, dataMode: effectiveDataMode, count: matchingCandidates.length }, "Fallback mode: matching imported candidates");
      }
    } else {
      // Mock mode: only mock candidates
      matchingCandidates = allCandidates.filter((c) => isMockSource(c.source));
      if (matchingCandidates.length === 0) {
        logger.warn({ runId }, "Mock mode: no mock candidates found — skipping matching. Run sourcing first.");
      } else {
        logger.info({ runId, dataMode: effectiveDataMode, count: matchingCandidates.length }, "Mock mode: matching mock candidates only");
      }
    }

    if (matchingCandidates.length === 0) {
      logger.warn({ runId }, "No eligible candidates for matching — skipping matching and shortlist");
    } else {
      await runCandidateMatching(runId, jobId, effectiveJob, insight, matchingCandidates);

      // Step 3: Shortlist (fetch fresh evaluations)
      const evaluations = await db
        .select()
        .from(aiEvaluationsTable)
        .where(eq(aiEvaluationsTable.runId, runId));

      const candidateMap = new Map(matchingCandidates.map((c) => [c.id, c]));
      const evalWithNames = evaluations.map((e) => ({
        candidateId: e.candidateId,
        candidateName: candidateMap.get(e.candidateId)?.name ?? "Unknown",
        score: e.score,
        recommendation: e.recommendation,
        strengths: (e.strengths ?? []) as string[],
        gaps: (e.gaps ?? []) as string[],
      }));

      if (evalWithNames.length > 0) {
        await runShortlist(runId, jobId, effectiveJob, insight, evalWithNames);
      }
    }

    await setRunStatus(runId, "completed");
    logger.info({ runId, jobId, effectiveDataMode }, "Workflow completed");
  } catch (err) {
    logger.error({ runId, jobId, err }, "Workflow failed");
    await setRunStatus(runId, "failed");
    await logStep(runId, "error", "failed", null, {
      error: err instanceof Error ? err.message : String(err),
    });
  }
}
