import {
  db,
  agentRunsTable,
  agentLogsTable,
  aiEvaluationsTable,
  jobInsightsTable,
  shortlistsTable,
  jobsTable,
  candidatesTable,
  applicationsTable,
  activeCandidateFilter,
} from "@workspace/db";
import type { VariantCriteria, DataMode, ScoringWeights } from "@workspace/db";
import { eq, ne, and, inArray } from "drizzle-orm";
import { logger } from "../../lib/logger";
import { validateEmail } from "../../lib/email-validation";
import { resolveProvider, resolveSourcingProvider, resolveEnrichmentProvider, resolveDecisionProvider } from "./providers";
import { DecisionQuotaExceededError } from "./providers/decision-interface";
import { deliberationsTable } from "@workspace/db";
import type { JobInsightResult, CandidateMatchResult, ShortlistResult } from "./engine-types";
import type { AgentProvider, SourcingCandidate, SourcingStats, SourcingRunResult, EnrichmentResult, EnrichmentCandidate } from "./providers";

export type { JobInsightResult, CandidateMatchResult, ShortlistResult };

// ── Source tag constants ──────────────────────────────────────────────────────

/** Candidates generated by the AI mock sourcing provider */
const SOURCE_MOCK = "Mock";
/** Candidates sourced via a Twin webhook provider */
const SOURCE_TWIN = "Twin";
/** Legacy mock source tag (from before strict data mode was introduced) */
const SOURCE_LEGACY_MOCK = "AI Generated / Mock Sourcing";

function isMockSource(source: string | null): boolean {
  return source === SOURCE_MOCK || source === SOURCE_LEGACY_MOCK;
}

// ── helpers ──────────────────────────────────────────────────────────────────

async function logStep(
  runId: number,
  step: string,
  status: "pending" | "running" | "completed" | "failed",
  input?: unknown,
  output?: unknown,
) {
  await db
    .insert(agentLogsTable)
    .values({ runId, step, status, input: input ?? null, output: output ?? null });
}

async function setRunStatus(runId: number, status: "running" | "completed" | "failed") {
  await db
    .update(agentRunsTable)
    .set({ status, updatedAt: new Date() })
    .where(eq(agentRunsTable.id, runId));
}

async function setRunDataMode(runId: number, dataMode: DataMode) {
  await db
    .update(agentRunsTable)
    .set({ dataMode, updatedAt: new Date() })
    .where(eq(agentRunsTable.id, runId));
}

// ── STEP 0: Sourcing (optional) ───────────────────────────────────────────────

async function runSourcing(
  runId: number,
  jobId: number,
  job: { title: string; description: string; location: string; seniority: string; mustHaveSkills: string[] },
  insight: JobInsightResult,
  sourceTag: string,
  forceProvider?: import("./providers").AgentProvider,
): Promise<number[]> {
  await logStep(runId, "sourcing", "running", { jobTitle: job.title, sourceTag });

  const provider = forceProvider ?? (await resolveSourcingProvider()).provider;
  logger.info({ runId, step: "sourcing", provider: provider.name, sourceTag }, "Sourcing step dispatched");

  try {
    const rawSourcingResult = (await provider.run({
      step: "sourcing",
      runId,
      jobId,
      payload: { job, insight },
    })) as SourcingRunResult;

    // Providers may return either a bare array (legacy) or { candidates, stats }.
    // Normalize so the rest of the engine — and the sourcing log — can treat
    // both the same, while still surfacing GitHub-style filter counts.
    const candidates: SourcingCandidate[] = Array.isArray(rawSourcingResult)
      ? rawSourcingResult
      : rawSourcingResult.candidates;
    const sourcingStats: SourcingStats | null = Array.isArray(rawSourcingResult)
      ? null
      : rawSourcingResult.stats ?? null;

    // Deduplicate by githubUrl OR email OR linkedinUrl against existing
    // candidates. Any one signal is enough to identify the same person:
    // GitHub-sourced rows may have no email, Web Search (LinkedIn) results
    // have only a profile URL, and imported rows may have only an email.
    // Dedupe lookup ignores soft-deleted rows so a candidate the recruiter
    // trashed can be re-sourced (and re-applied to the job) instead of being
    // silently skipped against a tombstone in the trash bin.
    const existing = await db
      .select({
        email: candidatesTable.email,
        githubUrl: candidatesTable.githubUrl,
        linkedIn: candidatesTable.linkedIn,
      })
      .from(candidatesTable)
      .where(activeCandidateFilter);
    const existingEmails = new Set(
      existing.map((c) => c.email?.toLowerCase()).filter((v): v is string => !!v),
    );
    const existingGithub = new Set(
      existing.map((c) => c.githubUrl?.toLowerCase()).filter((v): v is string => !!v),
    );
    const existingLinkedIn = new Set(
      existing.map((c) => c.linkedIn?.toLowerCase()).filter((v): v is string => !!v),
    );

    const newCandidateIds: number[] = [];
    let skippedNoIdentity = 0;
    for (const c of candidates) {
      const emailKey = c.email?.toLowerCase() ?? null;
      const githubKey = c.githubUrl?.toLowerCase() || null;
      const linkedinKey = c.linkedinUrl?.toLowerCase() || null;
      // Require at least one durable identity signal — otherwise we cannot
      // dedupe on reruns and would create infinite duplicates of the same
      // generic-website hit.
      if (!emailKey && !githubKey && !linkedinKey) {
        logger.warn({ name: c.name }, "Sourcing skipped candidate with no identity signal");
        skippedNoIdentity++;
        continue;
      }
      if (githubKey && existingGithub.has(githubKey)) {
        logger.warn({ githubUrl: c.githubUrl }, "Sourcing skipped duplicate github URL");
        continue;
      }
      if (emailKey && existingEmails.has(emailKey)) {
        logger.warn({ email: c.email }, "Sourcing skipped duplicate email");
        continue;
      }
      if (linkedinKey && existingLinkedIn.has(linkedinKey)) {
        logger.warn({ linkedinUrl: c.linkedinUrl }, "Sourcing skipped duplicate linkedin URL");
        continue;
      }
      if (emailKey) existingEmails.add(emailKey);
      if (githubKey) existingGithub.add(githubKey);
      if (linkedinKey) existingLinkedIn.add(linkedinKey);

      // Validate the discovered email so recruiters don't waste outreach on
      // dead addresses. We use a lightweight MX-record lookup (no third-party
      // provider needed). The check never throws — on infra failure we mark
      // the address "unchecked" and let the recruiter decide.
      const emailToValidate = c.email || null;
      const validation = emailToValidate
        ? await validateEmail(emailToValidate)
        : { status: "invalid" as const, reason: "No email address" };

      const [inserted] = await db
        .insert(candidatesTable)
        .values({
          name: c.name,
          email: c.email || null,
          linkedIn: c.linkedinUrl || null,
          summary: c.summary || null,
          skills: c.skills,
          headline: c.headline || null,
          location: c.location || null,
          currentCompany: c.currentCompany || null,
          githubUrl: c.githubUrl || null,
          githubUsername: c.username || null,
          sourcingConfidence: c.confidence ?? null,
          source: sourceTag,
          emailSource: c.emailSource ?? null,
          emailValidationStatus: validation.status,
          emailValidationReason: validation.reason,
          emailValidatedAt: emailToValidate ? new Date() : null,
        })
        .returning({ id: candidatesTable.id });

      newCandidateIds.push(inserted.id);

      // Create application at "Sourced" stage
      await db.insert(applicationsTable).values({
        jobId,
        candidateId: inserted.id,
        stage: "Sourced",
        notes: `AI Generated — ${c.evidence}\nPotential risks: ${c.potentialRisks}`,
      });
    }

    await logStep(runId, "sourcing", "completed", { jobTitle: job.title, provider: provider.name, sourceTag }, {
      generated: candidates.length,
      saved: newCandidateIds.length,
      skippedNoIdentity,
      // Provider name + type are denormalized onto the log output so the
      // run-detail UI can label which provider (e.g. "Apify") produced the
      // numbers without having to re-fetch agent_provider rows or join input.
      providerName: provider.name,
      providerType: provider.type,
      // Persisted so the run-detail UI can explain why a "0 candidates" run
      // was actually filtered (empty bios / stale activity) vs. a broken search.
      stats: sourcingStats,
    });
    return newCandidateIds;
  } catch (err) {
    await logStep(runId, "sourcing", "failed", { jobTitle: job.title, provider: provider.name }, {
      providerName: provider.name,
      providerType: provider.type,
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 0b: Enrichment (optional) ───────────────────────────────────────────

/**
 * Returns true if a candidate needs enrichment — i.e. has sparse or placeholder data.
 * We only enrich candidates that are likely incomplete to avoid overwriting good data.
 */
function needsEnrichment(c: {
  source: string | null;
  summary: string | null;
  skills: string[];
  headline: string | null;
}): boolean {
  if (c.source === "LinkedIn Paste") return true;
  if (!c.summary || c.summary.startsWith("Imported from LinkedIn")) return true;
  if (c.skills.length === 0) return true;
  if (!c.headline) return true;
  return false;
}

async function runEnrichment(
  runId: number,
  jobId: number,
  job: { title: string; seniority: string; mustHaveSkills: string[] },
): Promise<void> {
  // Resolve provider — null means no provider is configured; enrichment is skipped
  const provider = await resolveEnrichmentProvider();
  if (!provider) {
    await logStep(runId, "enrichment", "failed", null, {
      note: "No enrichment provider is assigned. Configure one in Settings → Agent Providers → Workflow Step Assignments to enable enrichment.",
    });
    logger.info({ runId }, "Enrichment skipped: no provider configured");
    return;
  }

  // Only enrich candidates in this job's pipeline
  const jobApplications = await db
    .select({ candidateId: applicationsTable.candidateId })
    .from(applicationsTable)
    .where(eq(applicationsTable.jobId, jobId));

  if (jobApplications.length === 0) {
    logger.info({ runId }, "No candidates in pipeline — skipping enrichment");
    return;
  }

  const candidateIds = jobApplications.map((a) => a.candidateId);
  const allCandidates = await db
    .select()
    .from(candidatesTable)
    .where(and(inArray(candidatesTable.id, candidateIds), activeCandidateFilter));

  // Filter to only candidates with sparse / placeholder profiles
  const candidates = allCandidates.filter(needsEnrichment);

  if (candidates.length === 0) {
    logger.info({ runId }, "No candidates need enrichment — all profiles are already complete");
    await logStep(runId, "enrichment", "completed", { note: "All candidates already have complete profiles" }, {
      enriched: 0,
    });
    return;
  }

  await logStep(runId, "enrichment", "running", { candidateCount: candidates.length, provider: provider.name });
  logger.info({ runId, step: "enrichment", provider: provider.name, count: candidates.length }, "Enrichment step dispatched");

  const rawResponse = await provider.run({
    step: "enrichment",
    runId,
    jobId,
    payload: {
      candidates,
      jobContext: { title: job.title, seniority: job.seniority, mustHaveSkills: job.mustHaveSkills },
    },
  });

  logger.info(
    { runId, step: "enrichment", provider: provider.name, raw: JSON.stringify(rawResponse).slice(0, 500) },
    "Enrichment raw response",
  );

  const results = rawResponse as EnrichmentResult[];

  const now = new Date();
  let enrichedCount = 0;
  let partialCount = 0;
  let failedCount = 0;

  for (const r of results) {
    const confidence = typeof r.confidence === "number" ? Math.min(1, Math.max(0, r.confidence)) : 0;
    const missingSet = new Set<string>(Array.isArray(r.missingFields) ? r.missingFields : []);

    // Determine enrichment outcome based on confidence and missing fields
    const status: string =
      confidence >= 0.7 && missingSet.size === 0
        ? "enriched"
        : confidence >= 0.4
        ? "partial"
        : "failed";

    if (status === "enriched") enrichedCount++;
    else if (status === "partial") partialCount++;
    else failedCount++;

    // Only write fields that are actually present in the result and not listed as missing
    await db
      .update(candidatesTable)
      .set({
        ...(r.experienceSummary && !missingSet.has("summary") ? { summary: r.experienceSummary } : {}),
        ...(Array.isArray(r.skills) && r.skills.length > 0 && !missingSet.has("skills") ? { skills: r.skills } : {}),
        ...(r.enrichedHeadline && !missingSet.has("headline") ? { headline: r.enrichedHeadline } : {}),
        ...(r.currentCompany && !missingSet.has("currentCompany") ? { currentCompany: r.currentCompany } : {}),
        ...(r.location && !missingSet.has("location") ? { location: r.location } : {}),
        enrichedAt: now,
        enrichmentSource: provider.name,
        enrichmentConfidence: confidence,
        enrichmentStatus: status,
        updatedAt: now,
      })
      .where(eq(candidatesTable.id, r.candidateId));
  }

  logger.info(
    { runId, step: "enrichment", enrichedCount, partialCount, failedCount },
    "Enrichment normalized output",
  );

  await logStep(runId, "enrichment", "completed", { candidateCount: candidates.length, provider: provider.name }, {
    enriched: enrichedCount,
    partial: partialCount,
    failed: failedCount,
    avgConfidence: results.length > 0
      ? (results.reduce((s, r) => s + (typeof r.confidence === "number" ? r.confidence : 0), 0) / results.length).toFixed(2)
      : null,
  });
}

// ── STEP 1: Job Understanding ─────────────────────────────────────────────────

async function runJobUnderstanding(
  runId: number,
  jobId: number,
  job: { title: string; description: string; location: string; seniority: string; mustHaveSkills: string[] },
): Promise<JobInsightResult> {
  await logStep(runId, "job_understanding", "running", { jobTitle: job.title });

  const provider = await resolveProvider("job_understanding");
  logger.info({ runId, step: "job_understanding", provider: provider.name }, "Step dispatched");

  try {
    const result = (await provider.run({
      step: "job_understanding",
      runId,
      jobId,
      payload: { job },
    })) as JobInsightResult;

    await logStep(runId, "job_understanding", "completed", { jobTitle: job.title, provider: provider.name }, result);
    return result;
  } catch (err) {
    await logStep(runId, "job_understanding", "failed", { jobTitle: job.title, provider: provider.name }, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 2: Candidate Matching ────────────────────────────────────────────────

// ── Data confidence score ─────────────────────────────────────────────────────
// Derived entirely from profile metadata — independent of AI fit scoring.
// Measures how complete and verifiable the candidate's profile is (0-100).

type CandidateForConfidence = {
  enrichmentStatus: string | null;
  enrichmentConfidence: number | null;
  linkedIn: string | null;
  skills: string[];
  summary: string | null;
  headline: string | null;
};

function computeDataConfidenceScore(c: CandidateForConfidence): {
  score: number;
  level: "High" | "Medium" | "Low";
  reason: string;
} {
  let points = 0;
  const parts: string[] = [];

  // Enrichment status — 0-40 pts
  if (c.enrichmentStatus === "enriched") {
    const confBonus = Math.round((c.enrichmentConfidence ?? 0.8) * 10);
    points += 30 + confBonus;
    parts.push("enriched profile");
  } else if (c.enrichmentStatus === "partial") {
    points += 20;
    parts.push("partially enriched");
  } else if (c.enrichmentStatus === "failed") {
    parts.push("enrichment failed");
  } else {
    parts.push("not enriched");
  }

  // LinkedIn URL present — 0-15 pts
  if (c.linkedIn && !c.linkedIn.includes("placeholder")) {
    points += 15;
    parts.push("LinkedIn URL present");
  }

  // Skills — 0-20 pts
  if (c.skills.length >= 5) {
    points += 20;
    parts.push(`${c.skills.length} skills listed`);
  } else if (c.skills.length >= 2) {
    points += 10;
    parts.push(`${c.skills.length} skills listed`);
  } else if (c.skills.length === 1) {
    points += 5;
    parts.push("1 skill listed");
  }

  // Summary — 0-20 pts
  if (c.summary && c.summary.length > 100) {
    points += 20;
    parts.push("detailed summary");
  } else if (c.summary && c.summary.length > 20) {
    points += 8;
    parts.push("brief summary");
  }

  // Headline — 0-5 pts
  if (c.headline) {
    points += 5;
    parts.push("headline present");
  }

  const score = Math.min(100, points);
  const level: "High" | "Medium" | "Low" = score >= 70 ? "High" : score >= 40 ? "Medium" : "Low";
  const reason = parts.length > 0 ? parts.join(", ") : "no profile data";
  return { score, level, reason };
}

/**
 * Runs targeted enrichment for a specific batch of low-confidence candidates
 * before they are evaluated. Updates candidate rows in the database in-place.
 * Non-throwing — the caller handles errors and falls back gracefully.
 */
async function runInlineEnrichmentForCandidates(
  runId: number,
  job: { title: string; seniority: string; mustHaveSkills: string[] },
  candidates: EnrichmentCandidate[],
  provider: AgentProvider,
): Promise<void> {
  const rawResponse = await provider.run({
    step: "enrichment",
    runId,
    jobId: 0,
    payload: {
      candidates,
      jobContext: { title: job.title, seniority: job.seniority, mustHaveSkills: job.mustHaveSkills },
    },
  });

  const results = rawResponse as EnrichmentResult[];
  const now = new Date();

  for (const r of results) {
    const confidence = typeof r.confidence === "number" ? Math.min(1, Math.max(0, r.confidence)) : 0;
    const missingSet = new Set<string>(Array.isArray(r.missingFields) ? r.missingFields : []);
    const status: string =
      confidence >= 0.7 && missingSet.size === 0 ? "enriched" : confidence >= 0.4 ? "partial" : "failed";

    await db
      .update(candidatesTable)
      .set({
        ...(r.experienceSummary && !missingSet.has("summary") ? { summary: r.experienceSummary } : {}),
        ...(Array.isArray(r.skills) && r.skills.length > 0 && !missingSet.has("skills") ? { skills: r.skills } : {}),
        ...(r.enrichedHeadline && !missingSet.has("headline") ? { headline: r.enrichedHeadline } : {}),
        ...(r.currentCompany && !missingSet.has("currentCompany") ? { currentCompany: r.currentCompany } : {}),
        ...(r.location && !missingSet.has("location") ? { location: r.location } : {}),
        enrichedAt: now,
        enrichmentSource: provider.name,
        enrichmentConfidence: confidence,
        enrichmentStatus: status,
        updatedAt: now,
      })
      .where(eq(candidatesTable.id, r.candidateId));
  }
}

async function runCandidateMatching(
  runId: number,
  jobId: number,
  job: { title: string; description: string; mustHaveSkills: string[]; seniority: string; scoringWeights: ScoringWeights },
  insight: JobInsightResult,
  candidates: Array<{
    id: number;
    name: string;
    email: string | null;
    skills: string[];
    summary: string | null;
    enrichmentStatus: string | null;
    enrichmentConfidence: number | null;
    linkedIn: string | null;
    headline: string | null;
    currentCompany: string | null;
    location: string | null;
    githubUrl: string | null;
  }>,
): Promise<void> {
  await logStep(runId, "candidate_matching", "running", { candidateCount: candidates.length });

  // ── Enrichment-first pre-screening ────────────────────────────────────────────
  // Before sending any candidate to the AI, measure data confidence.
  // Candidates below 50 points get inline enrichment if a provider is available.
  // If no provider is configured, scoring continues but those candidates are
  // flagged `requiresEnrichment = true` in the evaluation result. Never blocks.

  const requiresEnrichmentSet = new Set<number>();
  let candidatesForMatching = [...candidates];

  const lowConfCandidates = candidates.filter(
    (c) => computeDataConfidenceScore(c).score < 50,
  );

  if (lowConfCandidates.length > 0) {
    const enrichmentProvider = await resolveEnrichmentProvider();

    if (enrichmentProvider) {
      // Provider available — trigger targeted enrichment before evaluation
      logger.info(
        { runId, count: lowConfCandidates.length, candidates: lowConfCandidates.map((c) => c.name) },
        "Enrichment triggered before evaluation",
      );
      try {
        await runInlineEnrichmentForCandidates(runId, job, lowConfCandidates, enrichmentProvider);
        // Re-fetch the enriched rows so the AI sees updated profiles
        const enrichedIds = lowConfCandidates.map((c) => c.id);
        const refreshed = await db.select().from(candidatesTable).where(and(inArray(candidatesTable.id, enrichedIds), activeCandidateFilter));
        const refreshedMap = new Map(refreshed.map((c) => [c.id, c]));
        candidatesForMatching = candidatesForMatching.map((c) => refreshedMap.get(c.id) ?? c);
        logger.info({ runId, refreshed: refreshed.length }, "Re-fetched enriched candidates for matching");
      } catch (err) {
        // Enrichment failed — continue with original data; mark those as requiring enrichment
        logger.error({ runId, err }, "Inline enrichment failed — continuing with original candidate data");
        for (const c of lowConfCandidates) requiresEnrichmentSet.add(c.id);
      }
    } else {
      // No provider configured — score anyway but flag each candidate
      for (const c of lowConfCandidates) {
        logger.info(
          { runId, candidateId: c.id, candidateName: c.name },
          "Skipped full evaluation due to low confidence — no enrichment provider configured",
        );
        requiresEnrichmentSet.add(c.id);
      }
    }
  }

  const provider = await resolveProvider("candidate_matching");
  logger.info({ runId, step: "candidate_matching", provider: provider.name }, "Step dispatched");

  try {
    const results = (await provider.run({
      step: "candidate_matching",
      runId,
      jobId,
      payload: { job, insight, candidates: candidatesForMatching },
    })) as CandidateMatchResult[];

    const candidateMap = new Map(candidatesForMatching.map((c) => [c.id, c]));

    await Promise.all(
      results.map((r) => {
        const candidateData = candidateMap.get(r.candidateId);
        const dataConf = candidateData
          ? computeDataConfidenceScore(candidateData)
          : { score: 0, level: "Low" as const, reason: "candidate data unavailable" };

        const fitScore = r.fitScore ?? r.score;
        const decisionScore = Math.round(fitScore * (0.6 + 0.4 * dataConf.score / 100));

        const requiresEnrichment = requiresEnrichmentSet.has(r.candidateId);
        // Append the reliability warning to missingDataWarnings when enrichment was skipped
        const warnings = [...(r.missingDataWarnings ?? [])];
        if (requiresEnrichment) warnings.push("Low reliability — enrichment recommended");

        return db.insert(aiEvaluationsTable).values({
          runId,
          jobId,
          candidateId: r.candidateId,
          score: decisionScore, // backward-compat sort key = decisionScore
          fitScore,
          dataConfidenceScore: dataConf.score,
          decisionScore,
          confidenceLevel: dataConf.level,
          confidenceReason: r.confidenceReason ?? dataConf.reason,
          missingDataWarnings: warnings.length > 0 ? warnings : [],
          requiresEnrichment,
          strengths: r.strengths,
          gaps: r.gaps,
          risks: r.risks,
          recommendation: r.recommendation,
          scoreBreakdown: r.scoreBreakdown ?? null,
        });
      }),
    );

    await logStep(runId, "candidate_matching", "completed", { candidateCount: candidates.length, provider: provider.name }, {
      scores: results.map((r) => ({ name: r.candidateName, fitScore: r.fitScore ?? r.score, rec: r.recommendation })),
      enrichmentPreScreen: {
        lowConfidenceCount: lowConfCandidates.length,
        requiresEnrichmentCount: requiresEnrichmentSet.size,
      },
    });
  } catch (err) {
    await logStep(runId, "candidate_matching", "failed", { candidateCount: candidates.length, provider: provider.name }, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 3: Shortlist ─────────────────────────────────────────────────────────

async function runShortlist(
  runId: number,
  jobId: number,
  job: { title: string; description: string },
  insight: JobInsightResult,
  evaluations: Array<{
    candidateId: number;
    candidateName: string;
    score: number;
    recommendation: string;
    strengths: string[];
    gaps: string[];
  }>,
): Promise<void> {
  await logStep(runId, "shortlist", "running", { totalEvaluated: evaluations.length });

  const provider = await resolveProvider("shortlist_generation");
  logger.info({ runId, step: "shortlist_generation", provider: provider.name }, "Step dispatched");

  try {
    const top5 = [...evaluations].sort((a, b) => b.score - a.score).slice(0, 5);
    const summaries = (await provider.run({
      step: "shortlist_generation",
      runId,
      jobId,
      payload: { job, insight, evaluations: top5 },
    })) as ShortlistResult[];

    await db.insert(shortlistsTable).values({
      runId,
      jobId,
      rankedCandidateIds: top5.map((c) => c.candidateId),
      summaries,
    });

    await logStep(runId, "shortlist", "completed", { top5Count: top5.length, provider: provider.name }, { summaries });
  } catch (err) {
    await logStep(runId, "shortlist", "failed", {}, {
      error: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
}

// ── STEP 4 (optional): Decision (multi-pole deliberation) ─────────────────────

async function runDecisionStep(
  runId: number,
  jobId: number,
  job: { title: string; description: string; location?: string; seniority?: string; mustHaveSkills?: string[] },
  evaluations: Array<{ candidateId: number; candidateName: string; score: number }>,
  candidates: Array<typeof candidatesTable.$inferSelect>,
): Promise<void> {
  const provider = await resolveDecisionProvider();
  if (!provider) {
    // No decision provider configured — silently skip; this step is opt-in.
    return;
  }

  const top5 = [...evaluations].sort((a, b) => b.score - a.score).slice(0, 5);
  if (top5.length === 0) return;

  await logStep(runId, "decision", "running", {
    candidateCount: top5.length,
    provider: provider.name,
  });

  const candidateMap = new Map(candidates.map((c) => [c.id, c]));
  let succeeded = 0;
  let failed = 0;
  let quotaHit = false;

  for (const evalRow of top5) {
    const candidate = candidateMap.get(evalRow.candidateId);
    if (!candidate) continue;

    const [delibRow] = await db
      .insert(deliberationsTable)
      .values({
        candidateId: candidate.id,
        jobId,
        runId,
        stage: "Screening",
        status: "running",
      })
      .returning();

    try {
      const result = await provider.deliberate({
        candidate: {
          id: candidate.id,
          name: candidate.name,
          email: candidate.email ?? null,
          headline: candidate.headline ?? null,
          summary: candidate.summary ?? null,
          skills: (candidate.skills ?? []) as string[],
          linkedIn: candidate.linkedIn ?? null,
          githubUrl: candidate.githubUrl ?? null,
          location: candidate.location ?? null,
          currentCompany: candidate.currentCompany ?? null,
        },
        jd: {
          id: jobId,
          title: job.title,
          description: job.description,
          seniority: job.seniority ?? null,
          mustHaveSkills: (job.mustHaveSkills ?? []) as string[],
          location: job.location ?? null,
        },
        stage: "Screening",
      });
      await db
        .update(deliberationsTable)
        .set({ status: "completed", result, updatedAt: new Date() })
        .where(eq(deliberationsTable.id, delibRow.id));
      succeeded++;
    } catch (err) {
      const isQuota = err instanceof DecisionQuotaExceededError;
      if (isQuota) quotaHit = true;
      const message = err instanceof Error ? err.message : String(err);
      await db
        .update(deliberationsTable)
        .set({ status: "failed", error: message, updatedAt: new Date() })
        .where(eq(deliberationsTable.id, delibRow.id));
      logger.warn(
        { runId, candidateId: candidate.id, quota: isQuota, err },
        "Council deliberation failed",
      );
      failed++;
      // On quota, stop the rest of the batch — every subsequent call would also 402.
      if (isQuota) break;
    }
  }

  await logStep(
    runId,
    "decision",
    "completed",
    { candidateCount: top5.length, provider: provider.name },
    { succeeded, failed, quotaHit },
  );
}

// ── MAIN RUNNER ───────────────────────────────────────────────────────────────

export async function runWorkflowEngine(
  runId: number,
  jobId: number,
  options: {
    dataMode?: DataMode;
    runSourcing?: boolean;
    runEnrichment?: boolean;
    variantCriteria?: VariantCriteria;
    /** When set, only these candidate IDs are enriched (targeted improve-and-rerun path). */
    targetCandidateIds?: number[];
  } = {},
) {
  const dataMode: DataMode = options.dataMode ?? "mock";

  try {
    await setRunStatus(runId, "running");
    logger.info(
      { runId, jobId, dataMode, runSourcing: options.runSourcing, runEnrichment: options.runEnrichment, isVariant: !!options.variantCriteria },
      "Workflow started",
    );

    const [job] = await db.select().from(jobsTable).where(eq(jobsTable.id, jobId));
    if (!job) throw new Error(`Job ${jobId} not found`);

    // Apply variant criteria overrides if this is a variant run
    const vc = options.variantCriteria;
    const effectiveJob = vc
      ? {
          ...job,
          seniority: vc.seniority ?? job.seniority,
          mustHaveSkills: vc.mustHaveSkills ?? job.mustHaveSkills,
          description: vc.focusNote
            ? `${job.description}\n\n[Variant focus]: ${vc.focusNote}`
            : job.description,
        }
      : job;

    // Step 1: Job Understanding (always runs first)
    const insight = await runJobUnderstanding(runId, jobId, effectiveJob);
    await db.insert(jobInsightsTable).values({
      runId,
      jobId,
      mustHaveSkills: insight.mustHaveSkills,
      seniority: insight.seniority,
      evaluationCriteria: insight.evaluationCriteria,
      idealCandidateProfile: insight.idealCandidateProfile,
    });

    // Step 0: Sourcing (optional, runs after job understanding, before matching)
    if (options.runSourcing) {
      const { provider: sourcingProvider, isTwin } = await resolveSourcingProvider();

      if (dataMode === "real") {
        // Real mode: only "real" providers are allowed for sourcing (Twin/custom_webhook/github)
        if (!isTwin) {
          logger.warn({ runId }, "Real mode: no real provider assigned to sourcing — skipping sourcing step");
          await logStep(runId, "sourcing", "failed", null, {
            note: "Skipped: real data mode requires a real sourcing provider (Twin webhook, GitHub Agent, Web Search, or Apify). Assign one in Settings → Providers.",
          });
        } else {
          // Real mode with a real provider → tag with provider-specific source
          const realSourceTag =
            sourcingProvider.type === "github"
              ? "GitHub Agent"
              : sourcingProvider.type === "web_search"
              ? "Web Search"
              : sourcingProvider.type === "apify"
              ? "Apify"
              : sourcingProvider.type === "twin_agent"
              ? "Twin Agent Browser"
              : SOURCE_TWIN;
          try {
            await runSourcing(runId, jobId, effectiveJob, insight, realSourceTag, sourcingProvider);
          } catch (err) {
            // Twin sourcing failed in real mode → demote to fallback
            logger.error({ runId, err }, "Real mode: Twin sourcing failed — demoting run to fallback mode");
            await setRunDataMode(runId, "fallback");
            await logStep(runId, "sourcing", "failed", null, {
              error: err instanceof Error ? err.message : String(err),
              note: "Run demoted to fallback: Twin provider failed. Continuing with existing imported candidates.",
            });
          }
        }
      } else {
        // Mock mode: only use native mock sourcing (never Twin in mock mode)
        if (isTwin) {
          logger.warn({ runId }, "Mock mode: Twin provider is assigned to sourcing but data mode is mock — using native mock sourcing instead");
        }
        const { NativeOpenAISourcingProvider } = await import("./providers/native-openai-sourcing");
        const mockProvider = new NativeOpenAISourcingProvider(-1, "Native OpenAI Sourcing (mock)");
        try {
          await runSourcing(runId, jobId, effectiveJob, insight, SOURCE_MOCK, mockProvider);
        } catch (err) {
          logger.error({ runId, jobId, err }, "Mock sourcing failed — continuing with existing candidates");
          await logStep(runId, "sourcing", "failed", null, {
            error: err instanceof Error ? err.message : String(err),
            note: "Continuing workflow with existing candidates",
          });
        }
      }
    }

    // Step 0b: Enrichment (optional, runs after sourcing, before matching)
    if (options.runEnrichment) {
      try {
        if (options.targetCandidateIds && options.targetCandidateIds.length > 0) {
          // Targeted enrichment path: only enrich specific low-confidence candidates
          const enrichmentProvider = await resolveEnrichmentProvider();
          if (enrichmentProvider) {
            const targetCandidates = await db
              .select()
              .from(candidatesTable)
              .where(and(inArray(candidatesTable.id, options.targetCandidateIds), activeCandidateFilter));
            if (targetCandidates.length > 0) {
              await logStep(runId, "enrichment", "running", {
                candidateCount: targetCandidates.length,
                provider: enrichmentProvider.name,
                note: "Targeted enrichment for low-confidence candidates only",
              });
              logger.info(
                { runId, count: targetCandidates.length, provider: enrichmentProvider.name },
                "Targeted enrichment: enriching specific low-confidence candidates",
              );
              try {
                await runInlineEnrichmentForCandidates(runId, effectiveJob, targetCandidates, enrichmentProvider);
                await logStep(runId, "enrichment", "completed", { candidateCount: targetCandidates.length, provider: enrichmentProvider.name }, {
                  enriched: targetCandidates.length,
                  note: "Targeted enrichment completed",
                });
              } catch (err) {
                logger.error({ runId, err }, "Targeted enrichment failed — continuing with original candidate data");
                await logStep(runId, "enrichment", "failed", null, {
                  error: err instanceof Error ? err.message : String(err),
                  note: "Targeted enrichment failed — continuing with existing candidate data",
                });
              }
            }
          } else {
            await logStep(runId, "enrichment", "failed", null, {
              note: "No enrichment provider configured. Configure one in Settings → Agent Providers → Workflow Step Assignments.",
            });
            logger.info({ runId }, "Targeted enrichment skipped: no enrichment provider configured");
          }
        } else {
          await runEnrichment(runId, jobId, effectiveJob);
        }
      } catch (err) {
        // Enrichment failures are non-fatal — log and continue with existing candidate data.
        // There is NO silent fallback to a native provider here (see registry.ts).
        logger.error({ runId, jobId, err }, "Enrichment step failed — continuing without enrichment");
        await logStep(runId, "enrichment", "failed", null, {
          error: err instanceof Error ? err.message : String(err),
          note: "Continuing workflow without enrichment. No fallback provider is used.",
        });
      }
    }

    // Re-read current data mode (may have been updated to "fallback" during sourcing)
    const [currentRun] = await db.select({ dataMode: agentRunsTable.dataMode }).from(agentRunsTable).where(eq(agentRunsTable.id, runId));
    const effectiveDataMode: DataMode = currentRun?.dataMode ?? dataMode;

    // Step 2: Candidate Matching — enforce data mode separation. Soft-deleted
    // (trashed) candidates are excluded so a recruiter who just bulk-deleted
    // doesn't see them re-scored and resurface in the next workflow run.
    const allCandidates = await db.select().from(candidatesTable).where(activeCandidateFilter);

    let matchingCandidates: typeof allCandidates;
    if (effectiveDataMode === "real") {
      // Real mode: only non-mock candidates (imported + Twin)
      matchingCandidates = allCandidates.filter((c) => !isMockSource(c.source));
      if (matchingCandidates.length === 0) {
        logger.warn({ runId }, "Real mode: no imported or Twin-sourced candidates found — skipping matching");
      } else {
        logger.info({ runId, dataMode: effectiveDataMode, count: matchingCandidates.length }, "Real mode: matching non-mock candidates only");
      }
    } else if (effectiveDataMode === "fallback") {
      // Fallback mode: use all non-mock candidates (Twin failed, use whatever is imported)
      matchingCandidates = allCandidates.filter((c) => !isMockSource(c.source));
      if (matchingCandidates.length === 0) {
        logger.warn({ runId }, "Fallback mode: no imported candidates found — skipping matching");
      } else {
        logger.info({ runId, dataMode: effectiveDataMode, count: matchingCandidates.length }, "Fallback mode: matching imported candidates");
      }
    } else {
      // Mock mode: only mock candidates
      matchingCandidates = allCandidates.filter((c) => isMockSource(c.source));
      if (matchingCandidates.length === 0) {
        logger.warn({ runId }, "Mock mode: no mock candidates found — skipping matching. Run sourcing first.");
      } else {
        logger.info({ runId, dataMode: effectiveDataMode, count: matchingCandidates.length }, "Mock mode: matching mock candidates only");
      }
    }

    if (matchingCandidates.length === 0) {
      logger.warn({ runId }, "No eligible candidates for matching — skipping matching and shortlist");
    } else {
      await runCandidateMatching(runId, jobId, effectiveJob, insight, matchingCandidates);

      // Step 3: Shortlist (fetch fresh evaluations)
      const evaluations = await db
        .select()
        .from(aiEvaluationsTable)
        .where(eq(aiEvaluationsTable.runId, runId));

      const candidateMap = new Map(matchingCandidates.map((c) => [c.id, c]));
      const evalWithNames = evaluations.map((e) => ({
        candidateId: e.candidateId,
        candidateName: candidateMap.get(e.candidateId)?.name ?? "Unknown",
        score: e.score,
        recommendation: e.recommendation,
        strengths: (e.strengths ?? []) as string[],
        gaps: (e.gaps ?? []) as string[],
      }));

      if (evalWithNames.length > 0) {
        await runShortlist(runId, jobId, effectiveJob, insight, evalWithNames);

        // Step 4 (optional): Decision — multi-pole deliberation per shortlisted candidate.
        // Skipped silently when no decision provider is configured.
        await runDecisionStep(runId, jobId, effectiveJob, evalWithNames, matchingCandidates);
      }
    }

    await setRunStatus(runId, "completed");
    logger.info({ runId, jobId, effectiveDataMode }, "Workflow completed");
  } catch (err) {
    logger.error({ runId, jobId, err }, "Workflow failed");
    await setRunStatus(runId, "failed");
    await logStep(runId, "error", "failed", null, {
      error: err instanceof Error ? err.message : String(err),
    });
  }
}
