/**
 * Daneel — default template for the open-source agentic recruiting engine.
 *
 * Daneel is the underlying engine. This template is the neutral, framework-y
 * surface shipped with the public open-source release: minimal vocabulary
 * overrides, the engine name as the product name, and the project's own
 * domain. Forks/templates (HiringAI, future commercial templates) override
 * copy and visuals on top of this baseline.
 */

export const branding = {
  // ── Identity ───────────────────────────────────────────────────────────────
  productName: "Daneel",
  productTagline: "The open-source agentic workflow engine for recruiting.",
  productDescription:
    "Daneel is an MIT-licensed agentic recruiting engine. Describe the role, plug in your providers, and run a 4-step workflow that sources, scores, and shortlists candidates with auditable explanations.",
  domain: "daneel.dev",
  supportEmail: "hello@daneel.dev",

  // ── Audience ───────────────────────────────────────────────────────────────
  primaryUser: "operator",
  primaryUserPlural: "recruiters & hiring teams",
  reportAudience: "hiring team",

  // ── Terminology overrides ──────────────────────────────────────────────────
  // Neutral, industry-standard recruiting vocabulary.
  terms: {
    candidate: "candidate",
    candidates: "candidates",
    job: "job",
    jobs: "jobs",
    hiringManager: "hiring manager",
    report: "report",
    pipeline: "pipeline",
    application: "application",
    workflow: "workflow",
  },

  // ── Visual identity ────────────────────────────────────────────────────────
  // Same dark, AI-native palette as HiringAI — the open-source UI shipped to
  // the public is the same surface, just rebranded to the engine name.
  colors: {
    primary: "#0B0B12",
    primaryFg: "#F5F7FA",
    accent: "#7C5CFF",
    accentFg: "#0B0B12",
    success: "#22D3A4",
    warning: "#FBBF24",
    danger: "#FB7185",
    surface: "#0F0F18",
    surfaceMuted: "#1A1B26",
    border: "#262838",
    text: "#F5F7FA",
    textMuted: "#9CA3B5",
  },

  // ── Typography ─────────────────────────────────────────────────────────────
  fonts: {
    sans: '"Geist", "Inter", system-ui, sans-serif',
    serif: '"Source Serif 4", Georgia, serif',
    mono: '"Geist Mono", "JetBrains Mono", ui-monospace, monospace',
  },

  // ── Default report framing ─────────────────────────────────────────────────
  reportDefaults: {
    coverTitle: "Candidate Shortlist",
    coverSubtitle: "Generated by Daneel",
    decisionSummaryTitle: "Shortlist",
    nextActionsTitle: "Recommended Next Steps",
    footerNote: "Generated by the Daneel agentic recruiting engine.",
  },

  // ── Pipeline stage labels ──────────────────────────────────────────────────
  // Standard recruiting funnel — neutral defaults.
  stageLabels: {
    Sourced: "Sourced",
    Contacted: "Contacted",
    Screened: "Screened",
    Interview: "Interview",
    Offer: "Offer",
    Hired: "Hired",
    Rejected: "Rejected",
  },

  // ── Feature emphasis ───────────────────────────────────────────────────────
  // Same default capability set as HiringAI; templates can flip flags.
  featureFlags: {
    autoSource: true,
    autoOutreach: true,
    chatWithShortlist: true,
    slackInbox: true,
    oneClickHireDecision: true,
    skipApprovalFlow: true,
    bringYourOwnLLM: true,
    weeklyDigestEmail: true,
  },
} as const;

export type Branding = typeof branding;
export default branding;
